# Generated by Django 5.0.4 on 2024-04-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
    ]
