# Generated by Django 5.0.4 on 2024-04-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0005_remove_category_book_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
    ]
