# Generated by Django 5.0.4 on 2024-04-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0008_rename_category_book_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
