# Generated by Django 5.0.4 on 2024-04-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0010_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='/static/meme.jpeg', null=True, upload_to=''),
        ),
    ]
