# Generated by Django 5.0.4 on 2024-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0014_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ManyToManyField(to='book1.book'),
        ),
    ]
