# Generated by Django 5.0.4 on 2024-04-22 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0015_remove_review_book_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book1.book'),
            preserve_default=False,
        ),
    ]
