# Generated by Django 5.0.4 on 2024-04-22 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0015_remove_review_book_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=80),
        ),
    ]
