# Generated by Django 5.0.4 on 2024-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0016_review_active_review_created_remove_review_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='active',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ManyToManyField(to='book1.book'),
        ),
    ]
